name: Pylint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - if: always()
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint ruff black bandit pytype
    - if: always()
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files './Binary_tree/*.py')
    - if: always()
    - name: Analysing the code with ruff
      run: |
        ruff $(git ls-files './Binary_tree/*.py')
    - if: always()
    - name: Reformating the code with black
      run: |
        black $(git ls-files './Binary_tree/*.py')
    - if: always()
    - name: Analysing the code with bandit
      run: |
        bandit $(git ls-files './Binary_tree/*.py')
    - if: always()
    - name: Analysing the code with pytype
      run: |
        pytype $(git ls-files './Binary_tree/*.py')
